export const GET_ISSUES_COUNT_START = 'GET_ISSUES_COUNT_START';
export const GET_ISSUES_COUNT_SUCCESS = 'GET_ISSUES_COUNT_SUCCESS';
export const GET_OPEN_ISSUES_START = 'GET_OPEN_ISSUES_START';
export const GET_OPEN_ISSUES_SUCCESS = 'GET_OPEN_ISSUES_SUCCESS';
export const GET_COMMENTS_START = 'GET_COMMENTS_START';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
